name: Disable Default Pages Workflow

on:
  workflow_run:
    workflows: ["pages build and deployment"]
    types: [requested]

jobs:
  cancel-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Default Pages Workflow
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          workflow_id: ${{ github.event.workflow_run.id }}
